name: belteiis_kids
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flame: ^1.25.0
  gif_view: ^1.0.0
  flutter_screenutil: ^5.8.4
  crossword: ^1.3.2
  animated_button: ^0.3.1
  http: ^1.4.0
  fl_chart: ^1.0.0
  logger: ^2.5.0
  just_audio: ^0.9.35
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  device_preview: ^1.1.0
  platform: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audio/
    - assets/image/
    - assets/image/enductional_image.png
    - assets/image/mongkeys.png
    - assets/image/sparrow.png
    - assets/image/more.png
    - assets/image/chicken.png
    - assets/image/bear_forest.png
    - assets/image/line.png
    - assets/image/level_star_empty.png
    - assets/image/music.png
    - assets/image/icon_sound.png
    - assets/image/icons_charater.png

    
   

    
   
  fonts:
    - family: Rebellion
      fonts:
        - asset: assets/fonts/RebellionSquad-ZpprZ.ttf
    - family: ProtestRiot
      fonts:
        - asset: assets/fonts/ProtestRiot-Regular.ttf
    - family: Zany
      fonts:
        - asset: assets/fonts/Zany-6R21D.otf
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo2-Medium.ttf
    - family: PatrickHandSC
      fonts:
        - asset: assets/fonts/Chewy-Regular.ttf
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-VariableFont_wdth,wght.ttf
    - family: FredokaBold
      fonts:
        - asset: assets/fonts/Fredoka-Bold.ttf
  

